#pragma once

// Swift-friendly wrapper header
// This header aliases lbug_ functions to ladybug_ for Swift consumption
// while the underlying C++ implementation uses lbug_ naming

#include "lbug.h"

#ifdef __cplusplus
extern "C" {
#endif

// Alias all types
typedef lbug_system_config ladybug_system_config;
typedef lbug_database ladybug_database;
typedef lbug_connection ladybug_connection;
typedef lbug_prepared_statement ladybug_prepared_statement;
typedef lbug_query_result ladybug_query_result;
typedef lbug_flat_tuple ladybug_flat_tuple;
typedef lbug_logical_type ladybug_logical_type;
typedef lbug_value ladybug_value;
typedef lbug_internal_id_t ladybug_internal_id_t;
typedef lbug_date_t ladybug_date_t;
typedef lbug_timestamp_ns_t ladybug_timestamp_ns_t;
typedef lbug_timestamp_ms_t ladybug_timestamp_ms_t;
typedef lbug_timestamp_sec_t ladybug_timestamp_sec_t;
typedef lbug_timestamp_tz_t ladybug_timestamp_tz_t;
typedef lbug_timestamp_t ladybug_timestamp_t;
typedef lbug_interval_t ladybug_interval_t;
typedef lbug_query_summary ladybug_query_summary;
typedef lbug_int128_t ladybug_int128_t;
typedef lbug_data_type_id ladybug_data_type_id;
typedef lbug_state ladybug_state;

// Alias enum values
#define LADYBUG_ANY LBUG_ANY
#define LADYBUG_NODE LBUG_NODE
#define LADYBUG_REL LBUG_REL
#define LADYBUG_RECURSIVE_REL LBUG_RECURSIVE_REL
#define LADYBUG_SERIAL LBUG_SERIAL
#define LADYBUG_BOOL LBUG_BOOL
#define LADYBUG_INT64 LBUG_INT64
#define LADYBUG_INT32 LBUG_INT32
#define LADYBUG_INT16 LBUG_INT16
#define LADYBUG_INT8 LBUG_INT8
#define LADYBUG_UINT64 LBUG_UINT64
#define LADYBUG_UINT32 LBUG_UINT32
#define LADYBUG_UINT16 LBUG_UINT16
#define LADYBUG_UINT8 LBUG_UINT8
#define LADYBUG_INT128 LBUG_INT128
#define LADYBUG_DOUBLE LBUG_DOUBLE
#define LADYBUG_FLOAT LBUG_FLOAT
#define LADYBUG_DATE LBUG_DATE
#define LADYBUG_TIMESTAMP LBUG_TIMESTAMP
#define LADYBUG_TIMESTAMP_SEC LBUG_TIMESTAMP_SEC
#define LADYBUG_TIMESTAMP_MS LBUG_TIMESTAMP_MS
#define LADYBUG_TIMESTAMP_NS LBUG_TIMESTAMP_NS
#define LADYBUG_TIMESTAMP_TZ LBUG_TIMESTAMP_TZ
#define LADYBUG_INTERVAL LBUG_INTERVAL
#define LADYBUG_DECIMAL LBUG_DECIMAL
#define LADYBUG_INTERNAL_ID LBUG_INTERNAL_ID
#define LADYBUG_STRING LBUG_STRING
#define LADYBUG_BLOB LBUG_BLOB
#define LADYBUG_LIST LBUG_LIST
#define LADYBUG_ARRAY LBUG_ARRAY
#define LADYBUG_STRUCT LBUG_STRUCT
#define LADYBUG_MAP LBUG_MAP
#define LADYBUG_UNION LBUG_UNION
#define LADYBUG_POINTER LBUG_POINTER
#define LADYBUG_UUID LBUG_UUID

#define LadybugSuccess LbugSuccess
#define LadybugError LbugError

// Alias all functions - Database
#define ladybug_database_init lbug_database_init
#define ladybug_database_destroy lbug_database_destroy
#define ladybug_default_system_config lbug_default_system_config

// Connection
#define ladybug_connection_init lbug_connection_init
#define ladybug_connection_destroy lbug_connection_destroy
#define ladybug_connection_set_max_num_thread_for_exec lbug_connection_set_max_num_thread_for_exec
#define ladybug_connection_get_max_num_thread_for_exec lbug_connection_get_max_num_thread_for_exec
#define ladybug_connection_query lbug_connection_query
#define ladybug_connection_prepare lbug_connection_prepare
#define ladybug_connection_execute lbug_connection_execute
#define ladybug_connection_interrupt lbug_connection_interrupt
#define ladybug_connection_set_query_timeout lbug_connection_set_query_timeout

// PreparedStatement
#define ladybug_prepared_statement_destroy lbug_prepared_statement_destroy
#define ladybug_prepared_statement_is_success lbug_prepared_statement_is_success
#define ladybug_prepared_statement_get_error_message lbug_prepared_statement_get_error_message
#define ladybug_prepared_statement_bind_bool lbug_prepared_statement_bind_bool
#define ladybug_prepared_statement_bind_int64 lbug_prepared_statement_bind_int64
#define ladybug_prepared_statement_bind_int32 lbug_prepared_statement_bind_int32
#define ladybug_prepared_statement_bind_int16 lbug_prepared_statement_bind_int16
#define ladybug_prepared_statement_bind_int8 lbug_prepared_statement_bind_int8
#define ladybug_prepared_statement_bind_uint64 lbug_prepared_statement_bind_uint64
#define ladybug_prepared_statement_bind_uint32 lbug_prepared_statement_bind_uint32
#define ladybug_prepared_statement_bind_uint16 lbug_prepared_statement_bind_uint16
#define ladybug_prepared_statement_bind_uint8 lbug_prepared_statement_bind_uint8
#define ladybug_prepared_statement_bind_double lbug_prepared_statement_bind_double
#define ladybug_prepared_statement_bind_float lbug_prepared_statement_bind_float
#define ladybug_prepared_statement_bind_date lbug_prepared_statement_bind_date
#define ladybug_prepared_statement_bind_timestamp_ns lbug_prepared_statement_bind_timestamp_ns
#define ladybug_prepared_statement_bind_timestamp_sec lbug_prepared_statement_bind_timestamp_sec
#define ladybug_prepared_statement_bind_timestamp_tz lbug_prepared_statement_bind_timestamp_tz
#define ladybug_prepared_statement_bind_timestamp_ms lbug_prepared_statement_bind_timestamp_ms
#define ladybug_prepared_statement_bind_timestamp lbug_prepared_statement_bind_timestamp
#define ladybug_prepared_statement_bind_interval lbug_prepared_statement_bind_interval
#define ladybug_prepared_statement_bind_string lbug_prepared_statement_bind_string
#define ladybug_prepared_statement_bind_value lbug_prepared_statement_bind_value

// QueryResult
#define ladybug_query_result_destroy lbug_query_result_destroy
#define ladybug_query_result_is_success lbug_query_result_is_success
#define ladybug_query_result_get_error_message lbug_query_result_get_error_message
#define ladybug_query_result_get_num_columns lbug_query_result_get_num_columns
#define ladybug_query_result_get_column_name lbug_query_result_get_column_name
#define ladybug_query_result_get_column_data_type lbug_query_result_get_column_data_type
#define ladybug_query_result_get_num_tuples lbug_query_result_get_num_tuples
#define ladybug_query_result_get_query_summary lbug_query_result_get_query_summary
#define ladybug_query_result_has_next lbug_query_result_has_next
#define ladybug_query_result_get_next lbug_query_result_get_next
#define ladybug_query_result_has_next_query_result lbug_query_result_has_next_query_result
#define ladybug_query_result_get_next_query_result lbug_query_result_get_next_query_result
#define ladybug_query_result_to_string lbug_query_result_to_string
#define ladybug_query_result_reset_iterator lbug_query_result_reset_iterator
#define ladybug_query_result_get_arrow_schema lbug_query_result_get_arrow_schema
#define ladybug_query_result_get_next_arrow_chunk lbug_query_result_get_next_arrow_chunk

// FlatTuple
#define ladybug_flat_tuple_destroy lbug_flat_tuple_destroy
#define ladybug_flat_tuple_get_value lbug_flat_tuple_get_value
#define ladybug_flat_tuple_to_string lbug_flat_tuple_to_string

// DataType
#define ladybug_data_type_create lbug_data_type_create
#define ladybug_data_type_clone lbug_data_type_clone
#define ladybug_data_type_destroy lbug_data_type_destroy
#define ladybug_data_type_equals lbug_data_type_equals
#define ladybug_data_type_get_id lbug_data_type_get_id
#define ladybug_data_type_get_num_elements_in_array lbug_data_type_get_num_elements_in_array

// Value
#define ladybug_value_create_null lbug_value_create_null
#define ladybug_value_create_null_with_data_type lbug_value_create_null_with_data_type
#define ladybug_value_is_null lbug_value_is_null
#define ladybug_value_set_null lbug_value_set_null
#define ladybug_value_create_default lbug_value_create_default
#define ladybug_value_create_bool lbug_value_create_bool
#define ladybug_value_create_int8 lbug_value_create_int8
#define ladybug_value_create_int16 lbug_value_create_int16
#define ladybug_value_create_int32 lbug_value_create_int32
#define ladybug_value_create_int64 lbug_value_create_int64
#define ladybug_value_create_uint8 lbug_value_create_uint8
#define ladybug_value_create_uint16 lbug_value_create_uint16
#define ladybug_value_create_uint32 lbug_value_create_uint32
#define ladybug_value_create_uint64 lbug_value_create_uint64
#define ladybug_value_create_int128 lbug_value_create_int128
#define ladybug_value_create_float lbug_value_create_float
#define ladybug_value_create_double lbug_value_create_double
#define ladybug_value_create_internal_id lbug_value_create_internal_id
#define ladybug_value_create_date lbug_value_create_date
#define ladybug_value_create_timestamp_ns lbug_value_create_timestamp_ns
#define ladybug_value_create_timestamp_ms lbug_value_create_timestamp_ms
#define ladybug_value_create_timestamp_sec lbug_value_create_timestamp_sec
#define ladybug_value_create_timestamp_tz lbug_value_create_timestamp_tz
#define ladybug_value_create_timestamp lbug_value_create_timestamp
#define ladybug_value_create_interval lbug_value_create_interval
#define ladybug_value_create_string lbug_value_create_string
#define ladybug_value_create_list lbug_value_create_list
#define ladybug_value_create_struct lbug_value_create_struct
#define ladybug_value_create_map lbug_value_create_map
#define ladybug_value_clone lbug_value_clone
#define ladybug_value_copy lbug_value_copy
#define ladybug_value_destroy lbug_value_destroy
#define ladybug_value_get_list_size lbug_value_get_list_size
#define ladybug_value_get_list_element lbug_value_get_list_element
#define ladybug_value_get_struct_num_fields lbug_value_get_struct_num_fields
#define ladybug_value_get_struct_field_name lbug_value_get_struct_field_name
#define ladybug_value_get_struct_field_value lbug_value_get_struct_field_value
#define ladybug_value_get_map_size lbug_value_get_map_size
#define ladybug_value_get_map_key lbug_value_get_map_key
#define ladybug_value_get_map_value lbug_value_get_map_value
#define ladybug_value_get_recursive_rel_node_list lbug_value_get_recursive_rel_node_list
#define ladybug_value_get_recursive_rel_rel_list lbug_value_get_recursive_rel_rel_list
#define ladybug_value_get_data_type lbug_value_get_data_type
#define ladybug_value_get_bool lbug_value_get_bool
#define ladybug_value_get_int8 lbug_value_get_int8
#define ladybug_value_get_int16 lbug_value_get_int16
#define ladybug_value_get_int32 lbug_value_get_int32
#define ladybug_value_get_int64 lbug_value_get_int64
#define ladybug_value_get_uint8 lbug_value_get_uint8
#define ladybug_value_get_uint16 lbug_value_get_uint16
#define ladybug_value_get_uint32 lbug_value_get_uint32
#define ladybug_value_get_uint64 lbug_value_get_uint64
#define ladybug_value_get_int128 lbug_value_get_int128
#define ladybug_int128_t_from_string lbug_int128_t_from_string
#define ladybug_int128_t_to_string lbug_int128_t_to_string
#define ladybug_value_get_float lbug_value_get_float
#define ladybug_value_get_double lbug_value_get_double
#define ladybug_value_get_internal_id lbug_value_get_internal_id
#define ladybug_value_get_date lbug_value_get_date
#define ladybug_value_get_timestamp lbug_value_get_timestamp
#define ladybug_value_get_timestamp_ns lbug_value_get_timestamp_ns
#define ladybug_value_get_timestamp_ms lbug_value_get_timestamp_ms
#define ladybug_value_get_timestamp_sec lbug_value_get_timestamp_sec
#define ladybug_value_get_timestamp_tz lbug_value_get_timestamp_tz
#define ladybug_value_get_interval lbug_value_get_interval
#define ladybug_value_get_decimal_as_string lbug_value_get_decimal_as_string
#define ladybug_value_get_string lbug_value_get_string
#define ladybug_value_get_blob lbug_value_get_blob
#define ladybug_value_get_uuid lbug_value_get_uuid
#define ladybug_value_to_string lbug_value_to_string
#define ladybug_node_val_get_id_val lbug_node_val_get_id_val
#define ladybug_node_val_get_label_val lbug_node_val_get_label_val
#define ladybug_node_val_get_property_size lbug_node_val_get_property_size
#define ladybug_node_val_get_property_name_at lbug_node_val_get_property_name_at
#define ladybug_node_val_get_property_value_at lbug_node_val_get_property_value_at
#define ladybug_node_val_to_string lbug_node_val_to_string
#define ladybug_rel_val_get_id_val lbug_rel_val_get_id_val
#define ladybug_rel_val_get_src_id_val lbug_rel_val_get_src_id_val
#define ladybug_rel_val_get_dst_id_val lbug_rel_val_get_dst_id_val
#define ladybug_rel_val_get_label_val lbug_rel_val_get_label_val
#define ladybug_rel_val_get_property_size lbug_rel_val_get_property_size
#define ladybug_rel_val_get_property_name_at lbug_rel_val_get_property_name_at
#define ladybug_rel_val_get_property_value_at lbug_rel_val_get_property_value_at
#define ladybug_rel_val_to_string lbug_rel_val_to_string
#define ladybug_destroy_string lbug_destroy_string
#define ladybug_destroy_blob lbug_destroy_blob

// QuerySummary
#define ladybug_query_summary_destroy lbug_query_summary_destroy
#define ladybug_query_summary_get_compiling_time lbug_query_summary_get_compiling_time
#define ladybug_query_summary_get_execution_time lbug_query_summary_get_execution_time

// Utility functions
#define ladybug_timestamp_ns_to_tm lbug_timestamp_ns_to_tm
#define ladybug_timestamp_ms_to_tm lbug_timestamp_ms_to_tm
#define ladybug_timestamp_sec_to_tm lbug_timestamp_sec_to_tm
#define ladybug_timestamp_tz_to_tm lbug_timestamp_tz_to_tm
#define ladybug_timestamp_to_tm lbug_timestamp_to_tm
#define ladybug_timestamp_ns_from_tm lbug_timestamp_ns_from_tm
#define ladybug_timestamp_ms_from_tm lbug_timestamp_ms_from_tm
#define ladybug_timestamp_sec_from_tm lbug_timestamp_sec_from_tm
#define ladybug_timestamp_tz_from_tm lbug_timestamp_tz_from_tm
#define ladybug_timestamp_from_tm lbug_timestamp_from_tm
#define ladybug_date_to_string lbug_date_to_string
#define ladybug_date_from_string lbug_date_from_string
#define ladybug_date_to_tm lbug_date_to_tm
#define ladybug_date_from_tm lbug_date_from_tm
#define ladybug_interval_to_difftime lbug_interval_to_difftime
#define ladybug_interval_from_difftime lbug_interval_from_difftime

// Version
#define ladybug_get_version lbug_get_version
#define ladybug_get_storage_version lbug_get_storage_version

#ifdef __cplusplus
}
#endif
